-- Práctica #4: Consultas Avanzadas y Joins
-- Alumnos:
-- * Paredes Zamudio Luis Daniel
-- * Rivera Morales David
-- * Tapia Hernandez Carlos Alberto


-- * Sección #1: Creacion de Tablas

-- * Especificaciones de Desarollo
-- *
-- * - La base de datos debe incluir una tabla que almacene la informacion de los Empleados,
-- * incluyendo atributos como el employee id, first name, last name, email, hire date, y
-- * salary. Cada empleado debe estar asignado a un Departamento.
-- *
-- * - Los Departamentos deben ser gestionados en una tabla separada, con atributos como
-- * department id, department name, y manager id. Cada departamento tiene un gerente,
-- * que es un empleado, y puede tener multiples empleados asignados.
-- *
-- * - Los Proyectos en la empresa deben ser gestionados en otra tabla, que incluye atributos
-- * como project id, project name, start date, end date, y budget. Cada proyecto puede estar
-- * asociado a multiples empleados, y cada empleado puede estar asignado a multiples proyectos.
-- *
-- * - Las Asignaciones de Proyectos deben ser gestionadas en una tabla que relacione a los empleados
-- * con los proyectos a los que estan asignados. Esta tabla debe incluir atributos como assignment_id,
-- * employee id, project id, role, y hours_worked.
-- *
-- * - Se deben implementar relaciones de clave foranea entre las tablas, como la relacion entre
-- * employee_id en la tabla de Empleados y manager_id en la tabla de Departamentos, y entre
-- * department_id en la tabla de Empleados y la tabla de Departamentos. También debe existir una
-- * relacion entre employee_id y project_id en la tabla de Asignaciones de Proyectos.
-- *
-- * - El esquema debe permitir la extracción de información agregada, como el salario promedio de los
-- * empleados en cada departamento, el numero total de horas trabajadas por empleado en cada proyecto
-- * y el presupuesto total asignado a proyectos activos.
-- *
-- * - El sistema debe permitir el manejo de Proveedores, que son entidades externas involucradas en los
-- * proyectos. Los proveedores tienen atributos como supplier_id, supplier_name y contact_info. Cada
-- * proveedor puede estar relacionado con multiples proyectos, pero cada proyecto solo tiene un provedor.
-- *
-- * - Se debe manejar la relación entre Clientes y Proyectos. Cada cliente, almacenado en una tabla con
-- * atributos como customer_id, customer_name, contact_info, y project_id, puede estar relacionado con uno
-- * o más proyectos, y cada proyecto puede estar relacionado con multiples clientes.

-- Se crea primero la tabla DEPARTMENTS para no tener una relacion ciclica entre esta y DEPARTMENTS.

CREATE TABLE MANAGERS (
    MANAGER_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FST_NAME VARCHAR2(50),
    LST_NAME VARCHAR2(50),
    DEPARTMENT_ID NUMBER
)

CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
    MANAGER_ID NUMBER,
    FOREIGN KEY (MANAGER_ID) REFERENCES MANAGERS(MANAGER_ID)
);

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    DEPARTMENT_ID NUMBER,
    HIRE_DATE DATE,
    SALARY NUMBER,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

-- Como EMPLOYEES y DEPARTMENTS en su creación no tienen la relación MANAGER_ID (para evitar ciclos), se actualizan ahora:

ALTER TABLE MANAGERS
    ADD CONSTRAINT DEPARTMENTS_FK_MANAGER FOREIGN KEY (
        MANAGER_ID
    )
        REFERENCES DEPARTMENTS(
            DEPARTMENT_ID
        );

-- CUSTOMERS y SUPPLIERS se crean de igual forma para evitar relaciones ciclicas. Tienen el mismo
-- tipo de atributos pero son usos de caso distintos.

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(100) NOT NULL,
    CONTACT_INFO VARCHAR2(200)
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    CONTACT_INFO VARCHAR2(200)
);

-- PROJECTS se crea en este punto para poder tener llaves foráneas a las dos tablas
-- anteriores. Aunque no se especifica en los documentos de la práctica, consideramos
-- que tiene sentido que un proyecto tenga un cliente asignado, por lo que se incluye
-- como llave foránea junto a una que apunte a SUPPLIER_ID.

CREATE TABLE PROJECTS (
    PROJECT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SUPPLIER_ID NUMBER,
    CUSTOMER_ID NUMBER, -- Añadido para la relación con CUSTOMERS
    PROJECT_NAME VARCHAR2(100) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    BUDGET NUMBER CHECK (BUDGET > 0),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Finalmente se crean PROJECT_ASIGNMENT y CUSTOMER_PROJECT. La primera, al ya tener
-- el resto de tablas creadas, puede tener una llave foránea que apunte a PROJECT_ID en
-- PROJECTS y otra que apunte a EMPLOYEE_ID en EMPLOYEES.

CREATE TABLE PROJECT_ASIGNMENT (
    ASSIGNMENT_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    PROJECT_ID NUMBER,
    EMPLOYEE_ID NUMBER,
    ROLL VARCHAR2(20),
    HOURS_WORKED NUMBER,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- Por su lado, CUSTOMER_PROJECT se crea para manejar la relación entre clientes y proyectos teniendo
-- llaves foráneas que apunten a CUSTOMER_ID en CUSTOMERS y a PROJECT_ID en PROJECTS.

CREATE TABLE CUSTOMER_PROJECT (
    CUSTOMER_ID NUMBER,
    PROJECT_ID NUMBER,
    PRIMARY KEY (CUSTOMER_ID, PROJECT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);