insert into Customers (customer_id, customer_name, contact_info) values (1, 'Alanson Bresman', 'PO Box 87646');
insert into Customers (customer_id, customer_name, contact_info) values (2, 'Paulita Cowope', 'Apt 642');
insert into Customers (customer_id, customer_name, contact_info) values (3, 'Murvyn Sykes', 'Room 1744');
insert into Customers (customer_id, customer_name, contact_info) values (4, 'Blake Novotni', 'Apt 1859');
insert into Customers (customer_id, customer_name, contact_info) values (5, 'Spenser Jarmyn', 'PO Box 83004');
insert into Customers (customer_id, customer_name, contact_info) values (6, 'Nefen Langabeer', 'Suite 63');
insert into Customers (customer_id, customer_name, contact_info) values (7, 'Kacy Spencock', '2nd Floor');
insert into Customers (customer_id, customer_name, contact_info) values (8, 'Eileen Dressel', 'Room 464');
insert into Customers (customer_id, customer_name, contact_info) values (9, 'Linus MacPadene', 'Room 858');
insert into Customers (customer_id, customer_name, contact_info) values (10, 'Sherm Greensted', 'Apt 932');
insert into Customers (customer_id, customer_name, contact_info) values (11, 'Orville Stollard', 'Room 183');
insert into Customers (customer_id, customer_name, contact_info) values (12, 'Griffin Kiely', '14th Floor');
insert into Customers (customer_id, customer_name, contact_info) values (13, 'Son Oppery', 'PO Box 79416');
insert into Customers (customer_id, customer_name, contact_info) values (14, 'Daffie Forkan', 'PO Box 7543');
insert into Customers (customer_id, customer_name, contact_info) values (15, 'Erv Mooring', '4th Floor');
insert into Customers (customer_id, customer_name, contact_info) values (16, 'Rennie Orrum', 'PO Box 71729');
insert into Customers (customer_id, customer_name, contact_info) values (17, 'Cal Ruthen', '2nd Floor');
insert into Customers (customer_id, customer_name, contact_info) values (18, 'Elmer Bellany', 'PO Box 4307');
insert into Customers (customer_id, customer_name, contact_info) values (19, 'Willette Fetteplace', 'PO Box 64068');
insert into Customers (customer_id, customer_name, contact_info) values (20, 'Catharina Goodlatt', 'Suite 66');
insert into Customers (customer_id, customer_name, contact_info) values (21, 'Elwyn Lemasney', '8th Floor');
insert into Customers (customer_id, customer_name, contact_info) values (22, 'Adamo Florez', '14th Floor');
insert into Customers (customer_id, customer_name, contact_info) values (23, 'Guillaume Beardsell', 'PO Box 43069');
insert into Customers (customer_id, customer_name, contact_info) values (24, 'Murray Paulisch', 'Room 958');
insert into Customers (customer_id, customer_name, contact_info) values (25, 'Annalise Upjohn', 'Apt 1742');
insert into Customers (customer_id, customer_name, contact_info) values (26, 'Isadora Colcomb', 'Suite 76');
insert into Customers (customer_id, customer_name, contact_info) values (27, 'Ernest Henrys', 'Room 1165');
insert into Customers (customer_id, customer_name, contact_info) values (28, 'Isis Drohun', 'Apt 259');
insert into Customers (customer_id, customer_name, contact_info) values (29, 'Denys Breeder', 'Apt 1447');
insert into Customers (customer_id, customer_name, contact_info) values (30, 'Paquito Leddy', 'Suite 72');
