insert into Departments (department_id, department_name) values (1, 'Engineering');
insert into Departments (department_id, department_name) values (2, 'Services');
insert into Departments (department_id, department_name) values (3, 'Services');
insert into Departments (department_id, department_name) values (4, 'Business Development');
insert into Departments (department_id, department_name) values (5, 'Accounting');
insert into Departments (department_id, department_name) values (6, 'Product Management');
insert into Departments (department_id, department_name) values (7, 'Sales');
insert into Departments (department_id, department_name) values (8, 'Research and Development');
insert into Departments (department_id, department_name) values (9, 'Marketing');
insert into Departments (department_id, department_name) values (10, 'Engineering');
insert into Departments (department_id, department_name) values (11, 'Legal');
insert into Departments (department_id, department_name) values (12, 'Business Development');
insert into Departments (department_id, department_name) values (13, 'Marketing');
insert into Departments (department_id, department_name) values (14, 'Human Resources');
insert into Departments (department_id, department_name) values (15, 'Services');
insert into Departments (department_id, department_name) values (16, 'Marketing');
insert into Departments (department_id, department_name) values (17, 'Business Development');
insert into Departments (department_id, department_name) values (18, 'Legal');
insert into Departments (department_id, department_name) values (19, 'Accounting');
insert into Departments (department_id, department_name) values (20, 'Research and Development');
insert into Departments (department_id, department_name) values (21, 'Legal');
insert into Departments (department_id, department_name) values (22, 'Business Development');
insert into Departments (department_id, department_name) values (23, 'Legal');
insert into Departments (department_id, department_name) values (24, 'Sales');
insert into Departments (department_id, department_name) values (25, 'Legal');
insert into Departments (department_id, department_name) values (26, 'Product Management');
insert into Departments (department_id, department_name) values (27, 'Engineering');
insert into Departments (department_id, department_name) values (28, 'Marketing');
insert into Departments (department_id, department_name) values (29, 'Human Resources');
insert into Departments (department_id, department_name) values (30, 'Human Resources');
insert into Departments (department_id, department_name) values (31, 'Marketing');
insert into Departments (department_id, department_name) values (32, 'Accounting');
insert into Departments (department_id, department_name) values (33, 'Human Resources');
insert into Departments (department_id, department_name) values (34, 'Human Resources');
insert into Departments (department_id, department_name) values (35, 'Research and Development');
insert into Departments (department_id, department_name) values (36, 'Accounting');
insert into Departments (department_id, department_name) values (37, 'Engineering');
insert into Departments (department_id, department_name) values (38, 'Research and Development');
insert into Departments (department_id, department_name) values (39, 'Business Development');
insert into Departments (department_id, department_name) values (40, 'Human Resources');
insert into Departments (department_id, department_name) values (41, 'Product Management');
insert into Departments (department_id, department_name) values (42, 'Business Development');
insert into Departments (department_id, department_name) values (43, 'Legal');
insert into Departments (department_id, department_name) values (44, 'Accounting');
insert into Departments (department_id, department_name) values (45, 'Support');
insert into Departments (department_id, department_name) values (46, 'Engineering');
insert into Departments (department_id, department_name) values (47, 'Accounting');
insert into Departments (department_id, department_name) values (48, 'Accounting');
insert into Departments (department_id, department_name) values (49, 'Legal');
insert into Departments (department_id, department_name) values (50, 'Product Management');
------
UPDATE Departments SET manager_id = 1 WHERE department_id = 40;
UPDATE Departments SET manager_id = 2 WHERE department_id = 29;
UPDATE Departments SET manager_id = 3 WHERE department_id = 10;
UPDATE Departments SET manager_id = 4 WHERE department_id = 30;
UPDATE Departments SET manager_id = 5 WHERE department_id = 24;
UPDATE Departments SET manager_id = 6 WHERE department_id = 44;
UPDATE Departments SET manager_id = 7 WHERE department_id = 31;
UPDATE Departments SET manager_id = 8 WHERE department_id = 11;
UPDATE Departments SET manager_id = 9 WHERE department_id = 46;
UPDATE Departments SET manager_id = 10 WHERE department_id = 34;
UPDATE Departments SET manager_id = 11 WHERE department_id = 6;
UPDATE Departments SET manager_id = 12 WHERE department_id = 48;
UPDATE Departments SET manager_id = 13 WHERE department_id = 46;
UPDATE Departments SET manager_id = 14 WHERE department_id = 13;
UPDATE Departments SET manager_id = 15 WHERE department_id = 24;
UPDATE Departments SET manager_id = 16 WHERE department_id = 30;
UPDATE Departments SET manager_id = 17 WHERE department_id = 13;
UPDATE Departments SET manager_id = 18 WHERE department_id = 37;
UPDATE Departments SET manager_id = 19 WHERE department_id = 6;
UPDATE Departments SET manager_id = 20 WHERE department_id = 9;
UPDATE Departments SET manager_id = 21 WHERE department_id = 50;
UPDATE Departments SET manager_id = 22 WHERE department_id = 13;
UPDATE Departments SET manager_id = 23 WHERE department_id = 20;
UPDATE Departments SET manager_id = 24 WHERE department_id = 20;
UPDATE Departments SET manager_id = 25 WHERE department_id = 27;
UPDATE Departments SET manager_id = 26 WHERE department_id = 35;
UPDATE Departments SET manager_id = 27 WHERE department_id = 30;
UPDATE Departments SET manager_id = 28 WHERE department_id = 41;
UPDATE Departments SET manager_id = 29 WHERE department_id = 20;
UPDATE Departments SET manager_id = 30 WHERE department_id = 1;
UPDATE Departments SET manager_id = 31 WHERE department_id = 32;
UPDATE Departments SET manager_id = 32 WHERE department_id = 35;
UPDATE Departments SET manager_id = 33 WHERE department_id = 37;
UPDATE Departments SET manager_id = 34 WHERE department_id = 19;
UPDATE Departments SET manager_id = 35 WHERE department_id = 32;
UPDATE Departments SET manager_id = 36 WHERE department_id = 15;
UPDATE Departments SET manager_id = 37 WHERE department_id = 42;
UPDATE Departments SET manager_id = 38 WHERE department_id = 47;
UPDATE Departments SET manager_id = 39 WHERE department_id = 43;
UPDATE Departments SET manager_id = 40 WHERE department_id = 12;
UPDATE Departments SET manager_id = 41 WHERE department_id = 39;
UPDATE Departments SET manager_id = 42 WHERE department_id = 34;
UPDATE Departments SET manager_id = 43 WHERE department_id = 21;
UPDATE Departments SET manager_id = 44 WHERE department_id = 48;
UPDATE Departments SET manager_id = 45 WHERE department_id = 31;
UPDATE Departments SET manager_id = 46 WHERE department_id = 25;
UPDATE Departments SET manager_id = 47 WHERE department_id = 4;
UPDATE Departments SET manager_id = 48 WHERE department_id = 28;
UPDATE Departments SET manager_id = 49 WHERE department_id = 7;
UPDATE Departments SET manager_id = 50 WHERE department_id = 45;